apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vegeta-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Vegeta is the Schema for the vegeta API
      displayName: Vegeta
      kind: Vegeta
      name: vegeta.vegeta.testing.io
      version: v1alpha1
  description: Manage distributed runs of the Vegeta HTTP load testing tool on Kubernetes through custom resources.
  displayName: Vegeta
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  - load
  - performance
  - http
  - http2
  - vegeta
  links:
  - name: Vegeta Operator
    url: https://vegeta-operator.domain
  maturity: alpha
  provider:
    name: fgiloux
    url: https://github.com/fgiloux/
  version: 0.0.0
