## Append samples you want in your CSV to this file as resources ##
resources:
- vegeta_v1alpha1_vegeta.yaml
- vegeta_cm_rootcerts.yaml
- vegeta_cm_targets.yaml
- vegeta_pvc.yaml
- vegeta_obc.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
