apiVersion: vegeta.testing.io/v1alpha1
kind: Vegeta
metadata:
  name: vegeta-sample
spec:
  # Add fields here
  attack:
    duration: "10s"
    rate:     "5/1s"
    target:   "https://kubernetes.default.svc.cluster.local:443/healthz"
  replicas: 1