# permissions for end users to view vegeta.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vegeta-viewer-role
rules:
- apiGroups:
  - vegeta.testing.io
  resources:
  - vegeta
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vegeta.testing.io
  resources:
  - vegeta/status
  verbs:
  - get
