= S3 app for the Vegeta operator
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./img
endif::[]
:toc:
:toc-placement!:

== Overview

This repository contains the code for creating a little app that allows the transfer of results and reports with an S3 bucket.

== Build from source

To build the app from source you will need

- to have go 1.15 or newer installed
- to clone this repository
- to call the go build command 

==  Run

The application can simply be run with:

  $ s3 -command download
  $ s3 -command upload

Parameters are passed to the application through environment variables:

* BUCKET_HOST: The server with the S3 service
* BUCKET_PORT: The port of the S3 service, 443 per default
* BUCKET_NAME: The name of the S3 bucket
* BUCKET_REGION: The S3 region (optional)
* AWS_ACCESS_KEY_ID: The ID for the authentication (optional)
* AWS_SECRET_ACCESS_KEY: The key for the authentication (optional)
* S3_SECURE: Wheter a secure connection (https) is to be used
* S3_OBJECT_PREFIX: A common prefix of the objects containing the files to download (only for the download command)
* S3_UPLOAD_FILE: The full path of the file to upload (only for the upload command) 

== License

The Vegeta operator is under Apache 2.0 license. See the https://github.com/fgiloux/vegeta-operator/blob/main/LICENSE[LICENSE] file for details.

