apiVersion: v1
data:
  client.key: |
    MIIEogIBAAKCAQEA1F6dQauY+R+gCgWlMcUL+kLz5hlfpHy0qpuNRwoyElas2AgT
    Cv7nWoIzxi4TFgsKL+PtBOByRye3p+4yUsQD7jVfcplph2fcsHXFI6a2+XRqOW+0
    j/NSUNEp8bwyGLsdMvH3bbyvIyfwIoowVxNzTEKxryQovjT841FWfPmMyd5eUh2x
    UNjmN+bW7O6O4thbPQy2GrvhvdtslV6Pr0zNBpsFhJkwCNOo/oGWjc3ofqFgEQdI
    9VsiT/PaEDCVQs7f6Mi13BQxbjTFZW1c4guoxWsHvSN3PXlXcVhxQ2QZ5rgnwvdF
    FXtncKpqY6lKsM0xd6c7bat0O0+02fF4MXYMGQIDAQABAoIBAE39wTrQzgkPeDK2
    CAjTGKb71551Sw6ZTbAqGCQytljNxARCUtwC6OvwTRtG6HN78m3MAst7sfw3tdbS
    P2Dt45Ojvj3T4VF87ytO1OtW2nOaMTiOsXz8GwrbBdBlEPDMJtkCy59dX+RFUocc
    wMv5tKoZBDAR03Sm+QhyYpTbAL1RZSrpLqC15WP2JwWwXjn5Fzbd3YIhPlF/6EMe
    rd0M44Z/rAeQWCNWYYVsXBbnld3UhbOLMpaV1DtcTCrkOSmQvjwHn2/LrvTWt5x1
    srHfolLtpV0s1VOz/jci8vN0h8QjFmY+rZ0gBcYAeKakFnv9Kf5chOIl8JA+pvsO
    xbXSLtECgYEA+NU4enWycYKmpY9WtLTLkr7O+fiPulsostutQaVRHLz2snX0PErG
    8unPOYWBd8rtNMrKV+DSRxn1dQbBq7xi1aDWZ2BYF49BXwbTZiZYc2ewrfxdCYDr
    5Y3BtjV+IQOIa2wt4oR/hQAgNsdKA9qeTW2DFe01kUDUcGhVXNqQ5S8CgYEA2nyH
    rnnBrzBtN6oDMnAsgow6MxetRsxGIQml5Ft45U6ALQdzOAhEDfuzwFfHOFsY7FkT
    kHBjIWY8QwIyPamLe973KZofPy2kr01mG+xOM634YTYNJ/9rxT8CDWXjo/VSxEft
    Ndo7HqnTWktxDIwy/yWDoMWnKzLSJ58zWZ7iYTcCgYA1Moh3jdAPemocPQ/BZGGd
    RtPDF0PLCJAj5NkejrRPm4p2TsdfWHE+H4Rg/MzYCnc58RzfOr5Z2w/h7Abdq1HJ
    8C/GPA+5QbQtF618Sjhgu8tG9wwA6yIDmpHOXZNQhYvVw3Pv2HnWulcovuRw/H0Z
    eo8q0eLA4gZI3dVaG5QcmwKBgBYPRr/GCVk/4XciUkpQax4PPH0WIeepDledmsNQ
    vQciAu0I+IgqxXxH8qEz+6hkAkMyxzfpMQkZQnJdkWcKbEvoejoYFpmRaTRN80ZU
    eJzdLtvZ0kA8mMwEjZd+txpB1cZ9oKS0UQ3Khc1zGonyyd9bEUw1SKii6/cWKuAc
    m6zHAoGAWsucCJsNlxB+qFTy33i/xo0ZLvoeIKFDiGgZ9FQ8DtC+2c8Diu0Pmr8I
    hUz9IXNDy2ZKpl8amAzAxNuORtRK7jQ5AKHlapHS3qUaDCVLLa6Y/BvBQV2ghIap
    Oy1YC1J5RdPmwcchWi/75B9WTKsUSaXEbym7K1rgXi8GRs+NLM8=
kind: Secret
metadata:
  name: client-key
type: Opaque
